### PR TITLE
add-calc-options

### PR DESCRIPTION
**Pull request by rlavendomme**
Added all required options for current and planed features as tick boxes in the GUI.
Small changes applied to file export functions to accommodate options.
Note: each calculation will result in a dedicated output folder to prevent overwriting. This is not an issue because output folder will not be created for test calculations when output options are not ticked.
Note 2: currently, the report creation option is ticked by default. This can be changed to "toggled off by default" if it seems more convenient.

Need to revamp the report creation. Will be done in a dedicated branch later.

### CODE REVIEW

**Comment by jmaglic** [comment]
Works fine on my machine. I think the GUI needs a complete rework though. Also, I don't like that every surface map gets a new folder. This is not how it should work in the final product (instead the user should select an option like "Export" or "Save") and I don't see the benefit for me as developer. All it does is force me to regularly delete that folder. But we can leave that in for now. Since I have not made any changes I will just go ahead and merge.

**Comment by rlavendomme** [comment]
> 
> 
> Works fine on my machine. I think the GUI needs a complete rework though. Also, I don't like that every surface map gets a new folder. This is not how it should work in the final product (instead the user should select an option like "Export" or "Save") and I don't see the benefit for me as developer. All it does is force me to regularly delete that folder. But we can leave that in for now. Since I have not made any changes I will just go ahead and merge.

The folder will bundle the report and surface map and these folder/files are only created if desired by the user. I don't see any reason to mix different reports and surface maps in a single folder since each surface map only represents one set of parameters that are written in the report.

As a user, I would be extremely annoyed by having surface map files roaming around without knowing what they correspond to if I tested several parameters (like probe radii).

Conveniently, if you want to delete all files from calculations based on a single structure, there is a parent output folder corresponding to this structure that can be deleted in one go.

Eventually, we'll change what is needed based on beta testers preferences.

**Comment by jmaglic** [comment]
> The folder will bundle the report and surface map and these folder/files are only created if desired by the user.
As it stands now this is not true. These files are created by default.
> As a user, I would be extremely annoyed by having surface map files roaming around without knowing what they correspond to if I tested several parameters (like probe radii).
Personally I'd be annoyed by potentially enormous files being stored in a random folder. I don't disagree that the output files should be stored separately but as we've talked about before, the files should be placed in a folder specified explicitly by the user. I believe we should eventually create a drop-down menu in the status bar, with an "Export" option which opens a new dialogue box where the user can specify the folder and output file name. This is standard practice in most programs I've used. But this should not be done before we sit down and make a Clear plan how the GUI should be restructured

**Comment by rlavendomme** [comment]
> > The folder will bundle the report and surface map and these folder/files are only created if desired by the user.
> 
> As it stands now this is not true. These files are created by default.
> 

These files/folders are not created by default in my case as long as you untick the "generate report file" option. We can keep it unticked by default if that is what is bothering you.
If despite all export options being unticked, you still have creation of files and folders, then it is a bug on your build/system. If this is the case, could you please open an issue?

**Pull request merged**
